---
- hosts: websever
  become: yes
  vars:
    build_number: '{{ BUILD_NUMBER }}'
    ms: '{{ ms }}'
  tasks:
      
    - name: login to jfrog
      shell: docker login -u kjnithya59@gmail.com -p Nit@0301@2000 trialmnnmoi.jfrog.io  
    
    - name: pull an image
      shell: docker pull trialmnnmoi.jfrog.io/jenkins-cicd-docker-cicd/app-a/{{ ms }}:{{ build_number }}

    - name: remove container
      shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 8111:8080 trialmnnmoi.jfrog.io/jenkins-cicd-docker-cicd/app-a/{{ ms }}:{{ build_number }}
 
   
